## @param replicas The number of replica
replicas: 1

## @param nameOverride Custom name
nameOverride: ""

## @param fullnameOverride The full custom name
fullnameOverride: ""

image:
  ## @param image.repository The repository name
  repository: ubuntu/squid
  ## @param image.pullPolicy The image pull policy
  pullPolicy: IfNotPresent
  ## @param image.tag The image tag
  tag: "6.10-24.10_edge"

## @param imagePullSecrets [array] The image pull secrets
imagePullSecrets: []

pvc:
  ## @param pvc.enabled Use PVC instead emptyDir for cache data
  enabled: true
  ## @param pvc.labels Set labels to PVC
  labels: {}
  ## @param pvc.annotations Set annotations to PVC
  annotations: {}
  ## @param pvc.spec The PVC spec
  spec: {}

## @param env Set environment variables to pod
env: {}

## @param envFrom [array] set environment variable from secret or configMap
envFrom: []

## @param secretNameConfig Mount config on pod from secret
secretNameConfig: ""

## @param config The squid configs
config: |
  httpd_suppress_version_string on
  acl localnet src 0.0.0.1-0.255.255.255	# RFC 1122 "this" network (LAN)
  acl localnet src 10.0.0.0/8		# RFC 1918 local private network (LAN)
  acl localnet src 100.64.0.0/10		# RFC 6598 shared address space (CGN)
  acl localnet src 169.254.0.0/16 	# RFC 3927 link-local (directly plugged) machines
  acl localnet src 172.16.0.0/12		# RFC 1918 local private network (LAN)
  acl localnet src 192.168.0.0/16		# RFC 1918 local private network (LAN)
  acl localnet src fc00::/7       	# RFC 4193 local private network range
  acl localnet src fe80::/10      	# RFC 4291 link-local (directly plugged) machines
  acl SSL_ports port 443
  acl Safe_ports port 80		# http
  acl Safe_ports port 21		# ftp
  acl Safe_ports port 443		# https
  acl Safe_ports port 70		# gopher
  acl Safe_ports port 210		# wais
  acl Safe_ports port 1025-65535	# unregistered ports
  acl Safe_ports port 280		# http-mgmt
  acl Safe_ports port 488		# gss-http
  acl Safe_ports port 591		# filemaker
  acl Safe_ports port 777		# multiling http
  acl CONNECT method CONNECT
  http_access deny !Safe_ports
  http_access deny CONNECT !SSL_ports
  http_access allow localhost manager
  http_access deny manager
  http_access allow localhost
  http_access allow localnet
  http_access deny all
  refresh_pattern ^ftp:		1440	20%	10080
  refresh_pattern ^gopher:	1440	0%	1440
  refresh_pattern -i (/cgi-bin/|\?) 0	0%	0
  refresh_pattern \/(Packages|Sources)(|\.bz2|\.gz|\.xz)$ 0 0% 0 refresh-ims
  refresh_pattern \/Release(|\.gpg)$ 0 0% 0 refresh-ims
  refresh_pattern \/InRelease$ 0 0% 0 refresh-ims
  refresh_pattern \/(Translation-.*)(|\.bz2|\.gz|\.xz)$ 0 0% 0 refresh-ims
  refresh_pattern .		0	20%	4320
  logfile_rotate 0


serviceAccount:
  ## @param serviceAccount.create Specifies whether a service account should be created
  create: true
  ## @param serviceAccount.annotations Annotations to add to the service account
  annotations: {}
  ## @param serviceAccount.name The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

## @param podAnnotations The pod annotation
podAnnotations: {}

## @param  securityContext [object] The pod security context
securityContext:
   capabilities:
     drop:
     - ALL
   readOnlyRootFilesystem: true
   runAsNonRoot: true
   runAsUser: 1000

service:
  ## @param service.type The service type
  type: ClusterIP
  ## @param service.port The service port
  port: 3128


ingress:
  ## @param ingress.enabled Set true to enable ingress
  enabled: false
  ## @param ingress.className The class name to use
  className: ''
  ## @param ingress.annotations The ingress annotations
  annotations: {}
  ## @param ingress.hosts[0].host The hostname
  ## @param ingress.hosts[0].paths[0].path the path
  ## @param ingress.hosts[0].paths[0].pathType The path type
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  ## @param ingress.tls[0].hosts The hosts over TLS
  tls:
    - hosts: 
       - chart-example.local



## @param resources [object] The resources
resources:
  limits:
    cpu: 20m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

autoscaling:
  ## @param autoscaling.enabled Set true to enable HPA
  enabled: false
  ## @param autoscaling.minReplicas The min replicas
  minReplicas: 1
  ## @param autoscaling.maxReplicas The max replicas
  maxReplicas: 3
  ## @param autoscaling.targetCPUUtilizationPercentage The treshold base on CPU
  targetCPUUtilizationPercentage: 80
  ## @param autoscaling.targetMemoryUtilizationPercentage The treshold base on Memory
  ## Set 0 to disable it
  targetMemoryUtilizationPercentage: 0

## @param nodeSelector The node selector
nodeSelector: {}

## @param tolerations [array] The toleration
tolerations: []

## @param affinity The affinity
affinity: {}

## @param priorityClassName the priority class name
priorityClassName: ""

## @param terminationGracePeriodSeconds The termintation grace periode
terminationGracePeriodSeconds: 60

networkPolicy:
  ## @param networkPolicy.enabled Set true to enable the networkPolicy
  enabled: true
  ## @param networkPolicy.namespaceSelector The source namespace selector allowed to access on 
  namespaceSelector: {}