{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "helmproj.fullname" . }}
  labels:
    {{- include "helmproj.labels" . | nindent 4 }}
spec:
  {{- if .Values.networkPolicy.namespaceSelector }}
  - from:
    - namespaceSelector:
        matchLabels:
          {{ .Values.networkPolicy.namespaceSelector . | nindent 6 }}
  {{- end }}
  ingress:
    - ports:
      - port: 3128
        protocol: TCP
  podSelector:
    matchLabels:
      {{- include "helmproj.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
{{- end }}