apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "helmproj.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- (include "helmproj.labels" .) | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels: {{ (include "helmproj.selectorLabels" .) | nindent 6 }}
  serviceName: {{ include "helmproj.fullname" . }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.annotations }}
        {{ toYaml .Values.annotations | nindent 8 }}
        {{- end }}
      labels:
        {{- include "helmproj.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: "OnRootMismatch"
      serviceAccountName: {{ include "helmproj.serviceAccountName" . }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: squid
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3128
              name: squid
              protocol: TCP
          {{- with .Values.env }}
          env: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.envFrom }}
          envFrom: {{ toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - SETUID
                - SETGID
                - CHOWN
                - NET_RAW
                - DAC_OVERRIDE
                - KILL
            {{- with .Values.securityContext }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          readinessProbe:
            tcpSocket:
              port: squid
            initialDelaySeconds: 30
            periodSeconds: 30
          volumeMounts:
            - name: data
              mountPath: /var/spool/squid
            - name: config
              mountPath: /etc/squid/squid.conf
              subPath: squid.conf
            {{- if .Values.secretNameConfig }}
            - name: secret-config
              mountPath: /etc/squid/conf.d/
            {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      volumes:
        - name: config
          configMap:
            name: {{ template "helmproj.fullname" . }}-config
        {{- if not .Values.pvc.enabled }}
        - name: data
          emptyDir: {}
        {{- end }}
        {{- if .Values.secretNameConfig }}
        - name: secret-config
          secret:
            secretName: {{ .Values.secretNameConfig }}
        {{- end }}
  {{- if .Values.pvc.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
      {{- with .Values.pvc.labels }}
      labels: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pvc.annotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
    spec: {{ toYaml .Values.pvc.spec | nindent 6 }}
  {{- end }}